import type { Metadata } from "next";
import "./globals.css";
import localFont from 'next/font/local'

const YekanBakh = localFont({
  src: [
    {
      path: "../../public/font/YekanBakhFaNum-Regular.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "../../public/font/YekanBakhFaNum-SemiBold.woff2",
      weight: "600",
      style: "normal",
    },
    {
      path: "../../public/font/YekanBakhFaNum-Bold.woff2",
      weight: "700",
      style: "normal",
    },
  ],
})


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased ${YekanBakh.className}`}
      >
        {children}
      </body>
    </html>
  );
}
